CREATE TABLE IF NOT EXISTS clinic_settings (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    clinic_name VARCHAR(100) NOT NULL,
    logo_path VARCHAR(255),
    email VARCHAR(100),
    phone VARCHAR(20),
    website VARCHAR(255),
    address TEXT,
    country VARCHAR(100),
    currency VARCHAR(10),
    working_days JSON,
    working_hours_start TIME,
    working_hours_end TIME,
    default_appointment_duration INT DEFAULT 30,
    doctor_name VARCHAR(100),
    license_number VARCHAR(50),
    degree VARCHAR(100),
    specialization VARCHAR(100),
    awards_recognition TEXT,
    signature_path VARCHAR(255),
    gst_number VARCHAR(50),
    tax_registration_number VARCHAR(50),
    holidays JSON,
    time_zone VARCHAR(100) DEFAULT 'UTC',
    appointment_reminder_before INT DEFAULT 24,
    cancellation_policy TEXT,
    social_media_links JSON,
    payment_methods JSON,
    invoice_prefix VARCHAR(10),
    invoice_footer_text TEXT,
    sms_notifications BOOLEAN DEFAULT false,
    email_notifications BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
); 